/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IMdiClose: typeof import('~icons/mdi/close')['default']
    IMdiSuccessCircleOutline: typeof import('~icons/mdi/success-circle-outline')['default']
  }
}
