name: build
run-name: build
on:
  workflow_call:
  workflow_dispatch: 
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm install -g pnpm && pnpm install
      - name: Build
        run: pnpm run build:app
      - name: Build web components
        run: pnpm run build:lib
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: dist
          path: dist/
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: dist-lib
          path: dist-lib/
