name: tests
run-name: tests
on:
  pull_request:
    types: [opened, closed]
    branches: [master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm install -g pnpm && pnpm install
      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps
      - name: Run Playwright tests
        run: pnpm exec playwright test
      - name: Run unit tests
        run: pnpm run test:unit
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/q
          retention-days: 30

  build:
    needs: test
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/build.yml
